FROM serversideup/php:8.4-cli-alpine

USER root

RUN install-php-extensions intl imagick gd

COPY --chown=www-data:www-data . .

RUN chmod -R 755 storage \
    && mkdir -p bootstrap/cache \
    && chmod -R 775 bootstrap/cache

RUN composer install \
    --ignore-platform-reqs \
    --no-interaction \
    --no-dev \
    --optimize-autoloader \
    --prefer-dist

RUN mkdir -p /var/www/html/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer \
    && chmod -R 775 /var/www/html/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer \
    && chown -R www-data:www-data /var/www/html/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer

USER www-data
